### ISSUE TITLE
01 (Single-page-cv) Submission Checklist:

### ISSUE THREAD

**Issue by jtoledom1** [jtoledom1/Roadmap-projects#1]
- [x] Semantically correct HTML structure.
- [x] Single-page layout with sections for education, skills, and career history.
- [x] SEO meta tags in the head section.
- [x] OG tags for better social media sharing.
- [x] A favicon linked in the head section.
